from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import main

class MainWindow(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog
        self.dialog.setObjectName("Dialog")
        self.dialog.resize(1555, 625)
        self.leftWidget = QtWidgets.QWidget(Dialog)
        self.leftWidget.setObjectName("leftWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.dialog)
        self.groupBox.setObjectName("groupBox")
        self.groupBox2 = QtWidgets.QGroupBox(self.dialog)
        self.groupBox2.setObjectName("groupBox2")
        self.groupBox3 = QtWidgets.QGroupBox(self.dialog)
        self.groupBox3.setObjectName("groupBox2")

        self.control_label = QtWidgets.QLabel(self.centralWidget)
        self.control_label.setGeometry(QtCore.QRect(0, 5, 60, 25))
        self.control_label.setObjectName("control_lineEdit")
        self.control_lineEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.control_lineEdit.setGeometry(QtCore.QRect(0, 30, 340, 580))
        self.control_lineEdit.setObjectName("control_lineEdit")
        self.horizontalLayout.addWidget(self.centralWidget)

        self.img_label = QtWidgets.QLabel(self.leftWidget)
        self.img_label.setGeometry(QtCore.QRect(10, 20, 65, 25))
        self.img_label.setObjectName("img_label")
        self.img_push_button = QtWidgets.QPushButton(self.leftWidget)
        self.img_push_button.setGeometry(QtCore.QRect(100, 20, 150, 25))
        self.img_push_button.setObjectName("img_push_button")
        self.demo_label = QtWidgets.QLabel(self.leftWidget)
        self.demo_label.setGeometry(QtCore.QRect(10, 100, 65, 25))
        self.demo_label.setObjectName("demo_label")
        self.demo_line_edit = QtWidgets.QPlainTextEdit(self.leftWidget)
        self.demo_line_edit.setObjectName("demo_line_edit")
        self.demo_line_edit.setGeometry(QtCore.QRect(75, 100, 200, 200))
        self.demo_push_button = QtWidgets.QPushButton(self.leftWidget)
        self.demo_push_button.setGeometry(QtCore.QRect(15, 130, 50, 25))
        self.demo_push_button.setObjectName("demo_push_button")        
        self.knnK_label = QtWidgets.QLabel(self.leftWidget)
        self.knnK_label.setGeometry(QtCore.QRect(10, 320, 65, 25))
        self.knnK_label.setObjectName("knnK_label")
        self.knnK_line_edit = QtWidgets.QLineEdit(self.leftWidget)
        self.knnK_line_edit.setObjectName("knnK_line_edit")
        self.knnK_line_edit.setGeometry(QtCore.QRect(75, 320, 100, 25))
        self.knnK_push_button = QtWidgets.QPushButton(self.leftWidget)
        self.knnK_push_button.setGeometry(QtCore.QRect(180, 320, 50, 25))
        self.knnK_push_button.setObjectName("knnK_push_button")
        self.knnModel_label = QtWidgets.QLabel(self.leftWidget)
        self.knnModel_label.setGeometry(QtCore.QRect(10, 350, 65, 25))
        self.knnModel_label.setObjectName("knnModel_label")
        self.knnModel_line_edit = QtWidgets.QLineEdit(self.leftWidget)
        self.knnModel_line_edit.setObjectName("knnModel_line_edit")
        self.knnModel_line_edit.setGeometry(QtCore.QRect(75, 350, 100, 25))
        self.knnModel_push_button = QtWidgets.QPushButton(self.leftWidget)
        self.knnModel_push_button.setGeometry(QtCore.QRect(180, 350, 50, 25))
        self.knnModel_push_button.setObjectName("knnModel_push_button")

        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.horizontalLayout1_0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_0.setObjectName("horizontalLayout1_0")
        self.division_1 = QtWidgets.QPushButton(self.groupBox)
        self.division_1.setObjectName("division_1")
        self.horizontalLayout1_0.addWidget(self.division_1)
        self.verticalLayout_1.addLayout(self.horizontalLayout1_0)             
        self.horizontalLayout1_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_1.setObjectName("horizontalLayout1_1")
        self.division_2 = QtWidgets.QPushButton(self.groupBox)
        self.division_2.setObjectName("division_page")
        self.horizontalLayout1_1.addWidget(self.division_2)
        self.verticalLayout_1.addLayout(self.horizontalLayout1_1)
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        self.division_3 = QtWidgets.QPushButton(self.groupBox)
        self.division_3.setObjectName("division_3")
        self.horizontalLayout1_2.addWidget(self.division_3)
        self.verticalLayout_1.addLayout(self.horizontalLayout1_2)
        self.horizontalLayout1_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_4.setObjectName("horizontalLayout1_4")
        self.division_4 = QtWidgets.QPushButton(self.groupBox)
        self.division_4.setObjectName("classification_info")
        self.horizontalLayout1_4.addWidget(self.division_4)
        self.verticalLayout_1.addLayout(self.horizontalLayout1_4)
        self.horizontalLayout.addWidget(self.groupBox)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout_2.setObjectName("verticalLayout_1")
        self.horizontalLayout1_0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_0.setObjectName("horizontalLayout1_0")
        self.feature_1 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_1.setObjectName("feature_1")
        self.horizontalLayout1_0.addWidget(self.feature_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_0)             
        self.horizontalLayout1_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_1.setObjectName("horizontalLayout1_1")
        self.feature_2 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_2.setObjectName("feature_2")
        self.horizontalLayout1_1.addWidget(self.feature_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_1)
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        self.feature_3 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_3.setObjectName("feature_3")
        self.horizontalLayout1_2.addWidget(self.feature_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_2)
        self.horizontalLayout1_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_3.setObjectName("horizontalLayout1_3")
        self.feature_4 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_4.setObjectName("feature_4")
        self.horizontalLayout1_3.addWidget(self.feature_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_3)
        self.horizontalLayout1_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_4.setObjectName("horizontalLayout1_4")
        self.feature_5 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_5.setObjectName("feature_5")
        self.horizontalLayout1_4.addWidget(self.feature_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_4)
        self.horizontalLayout1_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_5.setObjectName("horizontalLayout1_5")
        self.feature_6 = QtWidgets.QPushButton(self.groupBox2)
        self.feature_6.setObjectName("feature_6")
        self.horizontalLayout1_5.addWidget(self.feature_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_5)
        self.horizontalLayout1_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_6.setObjectName("horizontalLayout1_5")
        self.feature_push = QtWidgets.QPushButton(self.groupBox2)
        self.feature_push.setObjectName("feature_6")
        self.horizontalLayout1_6.addWidget(self.feature_push)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_6)           
        self.horizontalLayout.addWidget(self.groupBox2)

        
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout2_0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_0.setObjectName("horizontalLayout2_0")
        self.knnAlgorithm = QtWidgets.QPushButton(self.groupBox3)
        self.knnAlgorithm.setObjectName("knnAlgorithm")
        self.horizontalLayout2_0.addWidget(self.knnAlgorithm)
        self.verticalLayout_3.addLayout(self.horizontalLayout2_0)
        self.horizontalLayout2_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_1.setObjectName("horizontalLayout1_5")
        self.svmAlgorithm = QtWidgets.QPushButton(self.groupBox3)
        self.svmAlgorithm.setObjectName("classification_info")
        self.horizontalLayout2_1.addWidget(self.svmAlgorithm)
        self.verticalLayout_3.addLayout(self.horizontalLayout2_1)
        self.horizontalLayout.addWidget(self.groupBox3) 

        self.horizontalLayout.addWidget(self.leftWidget)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.dialog.setWindowTitle(_translate("Dialog", "面向对象影像分类小工具"))
        self.groupBox.setTitle(_translate("Dialog", "请选择分割方式"))
        self.groupBox2.setTitle(_translate("Dialog", "请选择想要提取的特征"))
        self.groupBox3.setTitle(_translate("Dialog", "请选择分类算法"))
        self.control_label.setText(_translate("Dialog", "Terminal"))
        self.img_label.setText(_translate("Dialog", "打开影像"))
        self.img_push_button.setText("打开")

        self.demo_label.setText(_translate("Dialog", "输入样本"))
        self.demo_push_button.setText(_translate("Dialog", "确认"))
        self.knnK_label.setText(_translate("Dialog", "输入k值"))
        self.knnK_push_button.setText(_translate("Dialog", "确认"))
        self.knnModel_label.setText(_translate("Dialog", "输入模式"))
        self.knnModel_push_button.setText(_translate("Dialog", "确认"))
        self.division_1.setText(_translate("Dialog", "分水岭分割"))
        self.division_2.setText(_translate("Dialog", "基于SLIC-K均值的图像分割SLIC"))
        self.division_3.setText(_translate("Dialog", "快速移位图像分割"))
        self.division_4.setText(_translate("Dialog", "基于菲尔森茨瓦布高效图的分割"))
        self.feature_1.setText(_translate("Dialog", "灰度均值"))
        self.feature_2.setText(_translate("Dialog", "灰度标准差 "))
        self.feature_3.setText(_translate("Dialog", "灰度最大值"))
        self.feature_4.setText(_translate("Dialog", "灰度最小值"))
        self.feature_5.setText(_translate("Dialog", "纹理(LBP直方图)"))
        self.feature_6.setText(_translate("Dialog", "面积"))
        self.feature_push.setText(_translate("Dialog", "确认"))
        self.knnAlgorithm.setText(_translate("Dialog", "KNN算法"))
        self.svmAlgorithm.setText(_translate("Dialog", "SVM算法"))